'use client';

import { createContext, useContext, useEffect, useState, useMemo } from 'react';
import { Language } from '@/types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  es: {
    // Dashboard
    'dashboard.location.success.title': 'Ubicación obtenida',
    'dashboard.location.success.message': 'Se detectó tu ubicación correctamente',
    'dashboard.location.unavailable.title': 'Ubicación no disponible',
    'dashboard.location.unavailable.message': 'Se utilizará la ubicación predeterminada de Manta',
    'dashboard.location.unsupported.title': 'Geolocalización no soportada',
    'dashboard.location.unsupported.message': 'Tu navegador no soporta geolocalización',
    'dashboard.restaurants.loaded.title': 'Restaurantes cargados',
    'dashboard.restaurants.loaded.message': 'Se encontraron {count} restaurantes cerca de ti',
    'dashboard.restaurants.error.title': 'Error al cargar restaurantes',
    'dashboard.restaurants.error.message': 'No se pudieron cargar los restaurantes. Intenta nuevamente.',
    'dashboard.loading.aria': 'Cargando dashboard',
    'dashboard.loading': 'Cargando dashboard...',
    'dashboard.sr.title': 'Dashboard de Restaurantes',
    'dashboard.welcome': '¡Bienvenido',
    'dashboard.subtitle': 'Descubre restaurantes increíbles cerca de ti',
    'dashboard.tabs.aria': 'Vista de restaurantes',
    'dashboard.tabs.map.aria': 'Vista de mapa',
    'dashboard.tabs.map': 'Mapa',
    'dashboard.tabs.list.aria': 'Vista de lista',
    'dashboard.tabs.list': 'Lista',
    'dashboard.selected.title': 'Restaurante Seleccionado',
    'dashboard.nearby.title': 'Restaurantes Cerca',
    'dashboard.nearby.count': '{count} restaurantes encontrados',
    'dashboard.loading.restaurants.aria': 'Cargando restaurantes',
    'dashboard.loading.restaurants': 'Cargando restaurantes...',
    'dashboard.select.restaurant': 'Seleccionar {name}',
    'dashboard.noresults': 'No se encontraron restaurantes con los filtros seleccionados',
    // Restaurant Details
    'restaurant.cuisine': 'Tipo de cocina',
    'restaurant.contact': 'Información de contacto',
    'restaurant.website': 'Sitio web',
    'restaurant.hours': 'Horarios de atención',
    'restaurant.seeAllHours': 'Ver todos los horarios',
    'restaurant.getDirections': 'Cómo llegar',
    'restaurant.viewOnMaps': 'Ver en Google Maps',
    'restaurant.reviews': 'Reseñas',
    'restaurant.seeAllReviews': 'Ver todas las reseñas',
    // About
    'about.subtitle': 'Conoce más sobre nuestra misión de conectar a las personas con los mejores restaurantes de Manta',
    'about.card.location.title': 'Ubicación Precisa',
    'about.card.location.desc': 'Utilizamos tecnología GPS avanzada para mostrar restaurantes cerca de ti',
    'about.card.community.title': 'Comunidad Local',
    'about.card.community.desc': 'Apoyamos a los restaurantes locales de Manta y promovemos la gastronomía ecuatoriana',
    'about.card.easy.title': 'Fácil de Usar',
    'about.card.easy.desc': 'Interfaz intuitiva y moderna diseñada para una experiencia de usuario excepcional',
    'about.card.love.title': 'Hecho con Amor',
    'about.card.love.desc': 'Desarrollado por ecuatorianos para ecuatorianos, con pasión por la buena comida',
    'about.history.title': 'Nuestra Historia',
    'about.history.p1': 'Manta Restaurants nació de la necesidad de conectar a los habitantes y visitantes de Manta con los mejores restaurantes de la ciudad. Como manabitas, entendemos la importancia de la gastronomía en nuestra cultura.',
    'about.history.p2': 'Nuestra plataforma utiliza tecnología de geolocalización para ayudarte a descubrir restaurantes cerca de ti, desde los tradicionales locales de mariscos hasta los modernos restaurantes de cocina internacional.',
    'about.history.p3': 'Creemos que cada comida es una oportunidad para crear memorias, y queremos ser parte de esos momentos especiales conectándote con los lugares perfectos para disfrutar de la mejor comida.',
    'about.location.city': 'Manta, Ecuador',
    'about.location.heart': 'El corazón de nuestra plataforma',
    'about.values.title': 'Nuestros Valores',
    'about.values.transparency.title': 'Transparencia',
    'about.values.transparency.desc': 'Mostramos información real y actualizada de todos los restaurantes',
    'about.values.simplicity.title': 'Simplicidad',
    'about.values.simplicity.desc': 'Hacemos que encontrar un buen restaurante sea fácil y rápido',
    'about.values.commitment.title': 'Compromiso Local',
    'about.values.commitment.desc': 'Apoyamos el crecimiento y desarrollo de la gastronomía local',
    // Contact
    'contact.subtitle': 'Ponte en contacto con nosotros para cualquier consulta o sugerencia',
    'contact.form.title': 'Envíanos un mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.name.placeholder': 'Tu nombre',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'tu@email.com',
    'contact.form.subject': 'Asunto',
    'contact.form.subject.placeholder': '¿En qué podemos ayudarte?',
    'contact.form.message': 'Mensaje',
    'contact.form.message.placeholder': 'Escribe tu mensaje aquí...',
    'contact.form.sending': 'Enviando...',
    'contact.form.send': 'Enviar mensaje',
    'contact.success': 'Tu mensaje ha sido enviado exitosamente. Te responderemos pronto.',
    'contact.info.title': 'Información de contacto',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Teléfono',
    'contact.info.location': 'Ubicación',
    'contact.info.hours': 'Horario de atención',
    'contact.info.hours.weekdays': 'Lunes - Viernes: 9:00 AM - 6:00 PM',
    'contact.info.hours.saturday': 'Sábados: 9:00 AM - 2:00 PM',
    'contact.faq.title': 'Preguntas frecuentes',
    'contact.faq.add.q': '¿Cómo agrego mi restaurante?',
    'contact.faq.add.a': 'Los restaurantes se muestran automáticamente desde Google Maps. Para mayor visibilidad, asegúrate de que tu restaurante esté registrado en Google My Business.',
    'contact.faq.free.q': '¿Es gratuito usar la plataforma?',
    'contact.faq.free.a': 'Sí, nuestra plataforma es completamente gratuita para todos los usuarios.',
    'contact.faq.report.q': '¿Cómo reporto información incorrecta?',
    'contact.faq.report.a': 'Puedes enviarnos un mensaje a través de este formulario con los detalles del problema.',
    // Home
    'home.title': 'Encuentra los Mejores Restaurantes en Manta',
    'home.subtitle': 'Descubre restaurantes cerca de ti con nuestra tecnología de geolocalización',
    'home.cta': 'Comenzar Ahora',
    'home.features.title': 'Características',
    'home.features.subtitle': 'Explora nuestras funcionalidades',
    'home.features.geolocation.title': 'Geolocalización',
    'home.features.geolocation.desc': 'Encuentra restaurantes cerca de tu ubicación con precisión GPS',
    'home.features.search.title': 'Búsqueda Avanzada',
    'home.features.search.desc': 'Filtra por tipo de cocina, precio, calificación y más',
    'home.features.realtime.title': 'Tiempo Real',
    'home.features.realtime.desc': 'Información actualizada de horarios y disponibilidad',
    'home.features.ratings.title': 'Calificaciones',
    'home.features.ratings.desc': 'Consulta reseñas y calificaciones de otros usuarios',
    'home.cta.title': '¡Empieza a explorar ahora!',
    'home.cta.subtitle': 'Únete a miles de usuarios que ya descubren los mejores restaurantes de Manta',
    'home.cta.button': 'Crear cuenta gratis',
    // Footer
    'footer.description': 'Descubre los mejores restaurantes de Manta con nuestra tecnología de geolocalización avanzada.',
    'footer.links.title': 'Enlaces',
    'footer.legal.title': 'Legal',
    'footer.legal.privacy': 'Privacidad',
    'footer.legal.terms': 'Términos',
    'footer.legal.cookies': 'Cookies',
    'footer.copyright': '© 2024 Manta Restaurants. Todos los derechos reservados.',
    'footer.made': 'Hecho con',
    'footer.location': 'en Ecuador',
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.name': 'Nombre',
    'auth.login.button': 'Iniciar Sesión',
    'auth.register.button': 'Registrarse',
    'auth.forgot.password': '¿Olvidaste tu contraseña?',
    'auth.reset.password': 'Restablecer contraseña',
    'auth.no.account': '¿No tienes cuenta?',
    'auth.have.account': '¿Ya tienes cuenta?',
    'auth.login.sr.title': 'Iniciar sesión en Geotipicos',
    'auth.login.subtitle': 'Accede a tu cuenta para explorar restaurantes',
    'auth.login.error.invalid': 'Credenciales inválidas',
    'auth.login.error.general': 'Error al iniciar sesión',
    'auth.login.email.required': 'El email es obligatorio',
    'auth.login.email.invalid': 'El email no es válido',
    'auth.login.password.required': 'La contraseña es obligatoria',
    'auth.login.password.length': 'La contraseña debe tener al menos 6 caracteres',
    'auth.login.loading': 'Iniciando sesión...',
    'auth.login.loading.message': 'Procesando inicio de sesión, por favor espera',
    'auth.password.show': 'Mostrar contraseña',
    'auth.password.hide': 'Ocultar contraseña',
    // Forgot Password
    'forgot.password.title': '¿Olvidaste tu contraseña?',
    'forgot.password.subtitle': 'Te enviaremos un enlace para restablecer tu contraseña',
    'forgot.password.email.help': 'Ingresa el email asociado a tu cuenta',
    'forgot.password.sending': 'Enviando...',
    'forgot.password.send': 'Enviar enlace de restablecimiento',
    'forgot.password.back': 'Volver al inicio de sesión',
    'forgot.password.loading.message': 'Enviando enlace de restablecimiento, por favor espera',
    'forgot.password.success': 'Si existe una cuenta con ese email, recibirás un enlace para restablecer tu contraseña.',
    'forgot.password.check.email': 'Hacer clic aquí para restablecer contraseña',
    // Reset Password
    'reset.password.sr.title': 'Restablecer contraseña - Geotipicos',
    'reset.password.title': 'Restablecer contraseña',
    'reset.password.subtitle': 'Ingresa tu nueva contraseña',
    'reset.password.new.password': 'Nueva contraseña',
    'reset.password.new.password.placeholder': 'Mínimo 6 caracteres',
    'reset.password.new.password.help': 'La contraseña debe tener al menos 6 caracteres',
    'reset.password.confirm.password': 'Confirmar contraseña',
    'reset.password.confirm.password.placeholder': 'Confirma tu nueva contraseña',
    'reset.password.confirm.password.help': 'Debe coincidir con la contraseña anterior',
    'reset.password.confirm.password.show': 'Mostrar confirmación de contraseña',
    'reset.password.confirm.password.hide': 'Ocultar confirmación de contraseña',
    'reset.password.loading': 'Restableciendo...',
    'reset.password.button': 'Restablecer contraseña',
    'reset.password.loading.message': 'Restableciendo contraseña, por favor espera',
    'reset.password.back': 'Volver al inicio de sesión',
    'reset.password.go.login': 'Ir al inicio de sesión',
    // Registration
    'register.sr.title': 'Registrarse en Geotipicos',
    'register.back.home': 'Regresar al inicio',
    'register.subtitle': 'Crea tu cuenta para comenzar a explorar',
    'register.placeholder.name': 'Tu nombre completo',
    'register.placeholder.email': 'tu@email.com',
    'register.placeholder.password': 'Mínimo 6 caracteres',
    'register.hide.password': 'Ocultar contraseña',
    'register.show.password': 'Mostrar contraseña',
    'register.help.password': 'La contraseña debe tener al menos 6 caracteres',
    'register.strength.label': 'Fortaleza',
    'register.strength.0': 'Débil',
    'register.strength.1': 'Débil',
    'register.strength.2': 'Media',
    'register.strength.3': 'Fuerte',
    'register.strength.4': 'Muy fuerte',
    'register.loading': 'Creando cuenta...',
    'register.loading.message': 'Creando tu cuenta, por favor espera',
    'register.error.name.required': 'El nombre es obligatorio',
    'register.error.email.required': 'El email es obligatorio',
    'register.error.email.invalid': 'El email no es válido',
    'register.error.password.required': 'La contraseña es obligatoria',
    'register.error.password.length': 'La contraseña debe tener al menos 6 caracteres',
    'register.error.create': 'Error al crear la cuenta',
    'register.error.register': 'Error al registrar usuario',
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.help': 'Ayuda',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',
    'nav.dashboard': 'Dashboard',
    // Search
    'search.placeholder': 'Buscar restaurantes...',
    'search.filters': 'Filtros',
    'search.filter.restaurant': 'Restaurante',
    'search.filter.fast_food': 'Comida Rápida',
    'search.filter.cafe': 'Café',
    'search.filter.bar': 'Bar',
    'search.filter.pizza': 'Pizza',
    'search.filter.seafood': 'Mariscos',
    'search.filter.italian': 'Italiana',
    'search.filter.chinese': 'China',
    'search.filter.mexican': 'Mexicana',
    'search.filter.vegetarian': 'Vegetariana',
    // Map & Restaurants
    // Map
    'map.loading': 'Cargando mapa...',
    'map.showMap': 'Ver Mapa',
    'map.showList': 'Ver Lista',
    'restaurant.distance': 'distancia',
    'restaurant.open': 'Abierto',
    'restaurant.closed': 'Cerrado',
    // UI Elements
    'notifications.title': 'Notificaciones',
    'notifications.empty': 'No tienes notificaciones',
    'theme.light': 'Tema Claro',
    'theme.dark': 'Tema Oscuro',
    'language.spanish': 'Español',
    'language.english': 'English',
    'loading.app': 'Cargando aplicación...',
    'loading.app.aria': 'Cargando aplicación',
    // Notifications
    'notification.success.title': 'Éxito',
    'notification.success.message': 'Operación completada exitosamente',
    'notification.info.title': 'Información',
    'notification.info.message': 'Esta es una notificación informativa',
    'notification.warning.title': 'Advertencia',
    'notification.warning.message': 'Ten cuidado con esta acción',
    'notification.error.title': 'Error',
    'notification.error.message': 'Ha ocurrido un error',
    // Help
    'help.subtitle': 'Encuentra respuestas a las preguntas más frecuentes',
    'help.search.placeholder': 'Buscar en la ayuda...',
    'help.category.getting_started': 'Comenzando',
    'help.category.location': 'Ubicación',
    'help.category.account': 'Cuenta',
    'help.q.register.q': '¿Cómo me registro?',
    'help.q.register.a': 'Puedes registrarte haciendo clic en el botón "Registrarse" en la parte superior derecha.',
    'help.q.requirements.q': '¿Qué necesito para usar la aplicación?',
    'help.q.requirements.a': 'Solo necesitas un navegador web moderno con geolocalización habilitada.',
    'help.q.app.q': '¿Cómo funciona la aplicación?',
    'help.q.app.a': 'La aplicación usa tu ubicación para encontrar restaurantes cerca de ti y mostrarlos en un mapa.',
    'help.q.geolocation.q': '¿Por qué necesitan mi ubicación?',
    'help.q.geolocation.a': 'Necesitamos tu ubicación para mostrarte restaurantes cerca de ti.',
    'help.q.inaccurate_location.q': '¿Qué hago si mi ubicación es incorrecta?',
    'help.q.inaccurate_location.a': 'Asegúrate de que la geolocalización esté habilitada en tu navegador.',
    'help.q.other_city.q': '¿Puedo buscar en otras ciudades?',
    'help.q.other_city.a': 'Actualmente solo mostramos restaurantes en Manta, Ecuador.',
    'help.q.change_password.q': '¿Cómo cambio mi contraseña?',
    'help.q.change_password.a': 'Ve a tu perfil y selecciona la opción de cambiar contraseña.',
    'help.q.filters.a': 'Puedes usar los filtros haciendo clic en el botón de filtro junto a la barra de búsqueda. Selecciona el tipo de cocina, rango de precios y otras opciones para refinar tu búsqueda.',
    'help.q.favorites.q': '¿Puedo guardar restaurantes favoritos?',
    'help.q.favorites.a': 'Esta funcionalidad estará disponible en futuras actualizaciones. Por ahora, puedes tomar nota de los restaurantes que más te gusten.',
    'help.q.language.q': '¿Cómo cambio el idioma?',
    'help.q.language.a': 'Puedes cambiar el idioma haciendo clic en el botón del globo terráqueo en la parte superior derecha y seleccionando entre español o inglés.',
    'help.noresults': 'No se encontraron resultados para "{searchQuery}"',
    'help.noresults.suggestion': 'Intenta con otros términos de búsqueda',
    'help.contact.title': '¿No encontraste lo que buscabas?',
    'help.contact.desc': 'Si no pudiste encontrar la respuesta a tu pregunta, no dudes en contactarnos. Estamos aquí para ayudarte.',
    'help.contact.email.label': 'Email:',
    'help.contact.phone.label': 'Teléfono:',
  },
  en: {
    // Dashboard
    'dashboard.location.success.title': 'Location obtained',
    'dashboard.location.success.message': 'Your location was detected correctly',
    'dashboard.location.unavailable.title': 'Location unavailable',
    'dashboard.location.unavailable.message': 'Default location for Manta will be used',
    'dashboard.location.unsupported.title': 'Geolocation not supported',
    'dashboard.location.unsupported.message': 'Your browser does not support geolocation',
    'dashboard.restaurants.loaded.title': 'Restaurants loaded',
    'dashboard.restaurants.loaded.message': '{count} restaurants found near you',
    'dashboard.restaurants.error.title': 'Error loading restaurants',
    'dashboard.restaurants.error.message': 'Could not load restaurants. Please try again.',
    'dashboard.loading.aria': 'Loading dashboard',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.sr.title': 'Restaurants Dashboard',
    'dashboard.welcome': 'Welcome, ',
    'dashboard.subtitle': 'Discover amazing restaurants near you',
    'dashboard.tabs.aria': 'Restaurants view',
    'dashboard.tabs.map.aria': 'Map view',
    'dashboard.tabs.map': 'Map',
    'dashboard.tabs.list.aria': 'List view',
    'dashboard.tabs.list': 'List',
    'dashboard.selected.title': 'Selected Restaurant',
    'dashboard.nearby.title': 'Nearby Restaurants',
    'dashboard.nearby.count': '{count} restaurants found',
    'dashboard.loading.restaurants.aria': 'Loading restaurants',
    'dashboard.loading.restaurants': 'Loading restaurants...',
    'dashboard.select.restaurant': 'Select {name}',
    'dashboard.noresults': 'No restaurants found with the selected filters',
    // Restaurant Details
    'restaurant.cuisine': 'Cuisine type',
    'restaurant.contact': 'Contact information',
    'restaurant.website': 'Website',
    'restaurant.hours': 'Opening hours',
    'restaurant.seeAllHours': 'See all hours',
    'restaurant.getDirections': 'Get directions',
    'restaurant.viewOnMaps': 'View on Google Maps',
    'restaurant.reviews': 'Reviews',
    'restaurant.seeAllReviews': 'See all reviews',
    // About
    'about.subtitle': 'Learn more about our mission to connect people with the best restaurants in Manta',
    'about.card.location.title': 'Accurate Location',
    'about.card.location.desc': 'We use advanced GPS technology to show restaurants near you',
    'about.card.community.title': 'Local Community',
    'about.card.community.desc': 'We support local restaurants in Manta and promote Ecuadorian gastronomy',
    'about.card.easy.title': 'Easy to Use',
    'about.card.easy.desc': 'Intuitive and modern interface designed for an exceptional user experience',
    'about.card.love.title': 'Made with Love',
    'about.card.love.desc': 'Developed by Ecuadorians for Ecuadorians, with a passion for good food',
    'about.history.title': 'Our Story',
    'about.history.p1': 'Manta Restaurants was born from the need to connect residents and visitors of Manta with the best restaurants in the city. As Manabitas, we understand the importance of gastronomy in our culture.',
    'about.history.p2': 'Our platform uses geolocation technology to help you discover restaurants near you, from traditional seafood places to modern international cuisine restaurants.',
    'about.history.p3': 'We believe that every meal is an opportunity to create memories, and we want to be part of those special moments by connecting you with the perfect places to enjoy the best food.',
    'about.location.city': 'Manta, Ecuador',
    'about.location.heart': 'The heart of our platform',
    'about.values.title': 'Our Values',
    'about.values.transparency.title': 'Transparency',
    'about.values.transparency.desc': 'We show real and updated information from all restaurants',
    'about.values.simplicity.title': 'Simplicity',
    'about.values.simplicity.desc': 'We make finding a good restaurant easy and fast',
    'about.values.commitment.title': 'Local Commitment',
    'about.values.commitment.desc': 'We support the growth and development of local gastronomy',
    // Contact
    'contact.subtitle': 'Get in touch with us for any questions or suggestions',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Name',
    'contact.form.name.placeholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'How can we help you?',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Write your message here...',
    'contact.form.sending': 'Sending...',
    'contact.form.send': 'Send message',
    'contact.success': 'Your message has been sent successfully. We will respond soon.',
    'contact.info.title': 'Contact information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.info.hours': 'Business hours',
    'contact.info.hours.weekdays': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.info.hours.saturday': 'Saturday: 9:00 AM - 2:00 PM',
    'contact.faq.title': 'Frequently asked questions',
    'contact.faq.add.q': 'How do I add my restaurant?',
    'contact.faq.add.a': 'Restaurants are automatically displayed from Google Maps. For greater visibility, make sure your restaurant is registered on Google My Business.',
    'contact.faq.free.q': 'Is the platform free to use?',
    'contact.faq.free.a': 'Yes, our platform is completely free for all users.',
    'contact.faq.report.q': 'How do I report incorrect information?',
    'contact.faq.report.a': 'You can send us a message through this form with the details of the problem.',
    // Home
    'home.title': 'Find the Best Restaurants in Manta',
    'home.subtitle': 'Discover restaurants near you with our geolocation technology',
    'home.cta': 'Get Started',
    'home.features.title': 'Features',
    'home.features.subtitle': 'Explore our functionalities',
    'home.features.geolocation.title': 'Geolocation',
    'home.features.geolocation.desc': 'Find restaurants near your location with GPS precision',
    'home.features.search.title': 'Advanced Search',
    'home.features.search.desc': 'Filter by cuisine type, price, rating and more',
    'home.features.realtime.title': 'Real Time',
    'home.features.realtime.desc': 'Updated information on schedules and availability',
    'home.features.ratings.title': 'Ratings',
    'home.features.ratings.desc': 'Check reviews and ratings from other users',
    'home.cta.title': 'Start exploring now!',
    'home.cta.subtitle': 'Join thousands of users who already discover the best restaurants in Manta',
    'home.cta.button': 'Create free account',
    // Footer
    'footer.description': 'Discover the best restaurants in Manta with our advanced geolocation technology.',
    'footer.links.title': 'Links',
    'footer.legal.title': 'Legal',
    'footer.legal.privacy': 'Privacy',
    'footer.legal.terms': 'Terms',
    'footer.legal.cookies': 'Cookies',
    'footer.copyright': '© 2024 Manta Restaurants. All rights reserved.',
    'footer.made': 'Made with',
    'footer.location': 'in Ecuador',
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.login.button': 'Login',
    'auth.register.button': 'Register',
    'auth.forgot.password': 'Forgot your password?',
    'auth.reset.password': 'Reset password',
    'auth.no.account': "Don't have an account?",
    'auth.have.account': 'Already have an account?',
    'auth.login.sr.title': 'Login to Geotipicos',
    'auth.login.subtitle': 'Access your account to explore restaurants',
    'auth.login.error.invalid': 'Invalid credentials',
    'auth.login.error.general': 'Login error',
    'auth.login.email.required': 'Email is required',
    'auth.login.email.invalid': 'Email is not valid',
    'auth.login.password.required': 'Password is required',
    'auth.login.password.length': 'Password must be at least 6 characters',
    'auth.login.loading': 'Logging in...',
    'auth.login.loading.message': 'Processing login, please wait',
    'auth.password.show': 'Show password',
    'auth.password.hide': 'Hide password',
    // Forgot Password
    'forgot.password.title': 'Forgot your password?',
    'forgot.password.subtitle': 'We will send you a link to reset your password',
    'forgot.password.email.help': 'Enter the email associated with your account',
    'forgot.password.sending': 'Sending...',
    'forgot.password.send': 'Send reset link',
    'forgot.password.back': 'Back to login',
    'forgot.password.loading.message': 'Sending reset link, please wait',
    'forgot.password.success': 'If an account with that email exists, you will receive a link to reset your password.',
    'forgot.password.check.email': 'Click here to reset password',
    // Reset Password
    'reset.password.sr.title': 'Reset password - Geotipicos',
    'reset.password.title': 'Reset password',
    'reset.password.subtitle': 'Enter your new password',
    'reset.password.new.password': 'New password',
    'reset.password.new.password.placeholder': 'Minimum 6 characters',
    'reset.password.new.password.help': 'Password must be at least 6 characters',
    'reset.password.confirm.password': 'Confirm password',
    'reset.password.confirm.password.placeholder': 'Confirm your new password',
    'reset.password.confirm.password.help': 'Must match the previous password',
    'reset.password.confirm.password.show': 'Show password confirmation',
    'reset.password.confirm.password.hide': 'Hide password confirmation',
    'reset.password.loading': 'Resetting...',
    'reset.password.button': 'Reset password',
    'reset.password.loading.message': 'Resetting password, please wait',
    'reset.password.back': 'Back to login',
    'reset.password.go.login': 'Go to login',
    // Registration
    'register.sr.title': 'Register at Geotipicos',
    'register.back.home': 'Back to home',
    'register.subtitle': 'Create your account to start exploring',
    'register.placeholder.name': 'Your full name',
    'register.placeholder.email': 'your@email.com',
    'register.placeholder.password': 'Minimum 6 characters',
    'register.hide.password': 'Hide password',
    'register.show.password': 'Show password',
    'register.help.password': 'Password must be at least 6 characters',
    'register.strength.label': 'Strength',
    'register.strength.0': 'Weak',
    'register.strength.1': 'Weak',
    'register.strength.2': 'Medium',
    'register.strength.3': 'Strong',
    'register.strength.4': 'Very strong',
    'register.loading': 'Creating account...',
    'register.loading.message': 'Creating your account, please wait',
    'register.error.name.required': 'Name is required',
    'register.error.email.required': 'Email is required',
    'register.error.email.invalid': 'Email is not valid',
    'register.error.password.required': 'Password is required',
    'register.error.password.length': 'Password must be at least 6 characters',
    'register.error.create': 'Error creating account',
    'register.error.register': 'Error registering user',
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.help': 'Help',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.dashboard': 'Dashboard',
    // Search
    'search.placeholder': 'Search restaurants...',
    'search.filters': 'Filters',
    'search.filter.restaurant': 'Restaurant',
    'search.filter.fast_food': 'Fast Food',
    'search.filter.cafe': 'Café',
    'search.filter.bar': 'Bar',
    'search.filter.pizza': 'Pizza',
    'search.filter.seafood': 'Seafood',
    'search.filter.italian': 'Italian',
    'search.filter.chinese': 'Chinese',
    'search.filter.mexican': 'Mexican',
    'search.filter.vegetarian': 'Vegetarian',
    // Map & Restaurants
    // Map
    'map.loading': 'Loading map...',
    'map.showMap': 'Show Map',
    'map.showList': 'Show List',
    'restaurant.distance': 'away',
    'restaurant.open': 'Open',
    'restaurant.closed': 'Closed',
    // UI Elements
    'notifications.title': 'Notifications',
    'notifications.empty': 'You have no notifications',
    'theme.light': 'Light Theme',
    'theme.dark': 'Dark Theme',
    'language.spanish': 'Español',
    'language.english': 'English',
    'loading.app': 'Loading application...',
    'loading.app.aria': 'Loading application',
    // Notifications
    'notification.success.title': 'Success',
    'notification.success.message': 'Operation completed successfully',
    'notification.info.title': 'Information',
    'notification.info.message': 'This is an informational notification',
    'notification.warning.title': 'Warning',
    'notification.warning.message': 'Be careful with this action',
    'notification.error.title': 'Error',
    'notification.error.message': 'An error has occurred',
    // Help
    'help.subtitle': 'Find answers to the most frequently asked questions',
    'help.search.placeholder': 'Search in help...',
    'help.category.getting_started': 'Getting Started',
    'help.category.location': 'Location',
    'help.category.account': 'Account',
    'help.q.register.q': 'How do I register?',
    'help.q.register.a': 'You can register by clicking the "Register" button at the top right.',
    'help.q.requirements.q': 'What do I need to use the application?',
    'help.q.requirements.a': 'You only need a modern web browser with geolocation enabled.',
    'help.q.app.q': 'How does the application work?',
    'help.q.app.a': 'The application uses your location to find restaurants near you and display them on a map.',
    'help.q.geolocation.q': 'Why do you need my location?',
    'help.q.geolocation.a': 'We need your location to show you restaurants near you.',
    'help.q.inaccurate_location.q': 'What do I do if my location is incorrect?',
    'help.q.inaccurate_location.a': 'Make sure geolocation is enabled in your browser.',
    'help.q.other_city.q': 'Can I search in other cities?',
    'help.q.other_city.a': 'We currently only show restaurants in Manta, Ecuador.',
    'help.q.change_password.q': 'How do I change my password?',
    'help.q.change_password.a': 'Go to your profile and select the change password option.',
    'help.q.filters.a': 'You can use the filters by clicking the filter button next to the search bar. Select cuisine type, price range, and other options to refine your search.',
    'help.q.favorites.q': 'Can I save favorite restaurants?',
    'help.q.favorites.a': 'This feature will be available in future updates. For now, you can take note of the restaurants you like the most.',
    'help.q.language.q': 'How do I change the language?',
    'help.q.language.a': 'You can change the language by clicking the globe button at the top right and selecting between Spanish or English.',
    'help.noresults': 'No results found for "{searchQuery}"',
    'help.noresults.suggestion': 'Try other search terms',
    'help.contact.title': 'Didn\'t find what you were looking for?',
    'help.contact.desc': 'If you couldn\'t find the answer to your question, feel free to contact us. We are here to help you.',
    'help.contact.email.label': 'Email:',
    'help.contact.phone.label': 'Phone:',
  },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };


  const contextValue = useMemo(() => {
    const t = (key: string): string => {
      return (translations[language] as Record<string, string>)[key] || key;
    };
    return {
      language,
      setLanguage: handleSetLanguage,
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};